title:         Manish A.Shetty  
description:   The official blog of Manish A.Shetty.
baseurl:       "Manishshetty.com"
url:           ""

# Build settings
markdown:      kramdown
paginate:      5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
